name: investing_organizer
description: Backend for Investing Organizer App
version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.0
  csv: ^5.0.0
  excel: ^2.0.0-null-safety-3
  in_date_range: ^1.0.0
  in_date_utils: ^1.0.1+1
  path: ^1.8.0
  string_ext: ^0.2.0
  tinkoff_invest: ^0.1.1

dev_dependencies:
  innim_lint: ^0.1.0
