name: investing_organizer
description: Backend for Investing Organizer App
version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.0

dev_dependencies:
  innim_lint: ^0.1.0
